### PR TITLE
Fix #491: Opening Send Feedback then backing out then re-entering shows prompt again.

### LINKED ISSUE #491: Tapping back in region confirmation dialog is treated as a "yes"
**Summary:** 

In the issue reporting process, when you first tap on "Send feedback" and you are prompted with the "Are you in the Tampa Bay region?", if you tap the back button and then tap on "Send feedback" again, it is treated as though you answered "Yes" to the region confirmation prompt dialog.

**Steps to reproduce:** 

1. Do a fresh install of OBA Android
2. Tap on "Send feedback"
3. Hit the back button when the dialog for "Are you in the Tampa Bay region?" is displayed
4. Tap on "Send feedback" again

**Expected behavior:** 

Prompt me again for the "Are you in the Tampa Bay region?"

**Observed behavior:** 

The list of feedback general categories is displayed, which (I believe) assumes that I answered "Yes" to the region confirmation dialog:

image

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Screenshots:** 

See above

### PR DESCRIPTION
**Pull request by azizmb9494**
Issue #491 fixed. Instead of the Validated Region ID preference being set instantly when the Dialog is showed, I added a member field to ReportActivity to keep track of the current region ID. In RegionDialog, once "Yes" is tapped, the validated region ID preference is set.

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @azizmb9494!

@cagryInside Could you please take a look at this PR and let me know if it looks good to you?  It should fix #491.  Feel free to leave comments in-line.

File: onebusaway-android/src/main/java/org/onebusaway/android/report/ui/ReportActivity.java [hunk 1]
```diff
@@ -65,9 +66,9 @@ protected void onCreate(Bundle savedInstanceState) {
             ObaRegion currentRegion = Application.get().getCurrentRegion();
 
             if (showValidateRegionDialog(currentRegion)) {
+                mRegionId = currentRegion.getId();
```
Comment (cagryInside) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/ReportActivity.java]: @azizmb9494 Could you please use `Bundle` to pass data to `RegionValidateDialog` fragment? Something like:

```
Bundle bundle = new Bundle();
bundle.putLong(key, regionId);
rvd.setArguments(bundle);
```
I think, we should try to avoid creating unnecessary members.

**Comment by cagryInside** [comment]
Thanks @azizmb9494, looks pretty good. Just one inline comment.

File: onebusaway-android/src/main/java/org/onebusaway/android/report/ui/ReportActivity.java (hunk 1 above)
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/ReportActivity.java]: Agreed, this would also be a cleaner separation between the current hosting Activity and the Fragment.

**Comment by azizmb9494** [comment]
Thanks @cagryInside! One question, RegionValidationDialog uses "Application.get().getCurrentRegion()" when building the message string, would it be safe just to get the ID from the current region like this on "Yes" tapped?

**Comment by cagryInside** [comment]
> Thanks @cagryInside! One question, RegionValidationDialog uses "Application.get().getCurrentRegion()" when building the message string, would it be safe just to get the ID from the current region like this on "Yes" tapped?

Good point! Yes, it would be safe to use, because we already check the `region` before opening the `fragment`.

**Comment by azizmb9494** [comment]
Thanks @barbeau & @cagryInside! Fixed and pushed!

**Comment by cagryInside** [comment]
@azizmb9494 thanks. It looks pretty good now. 
One small thing, could you please add the issue number to the commit message? Something like `"Fix #492 - Validated Region ID only set on tap instead."` Like that, Github will automatically link your commit with the issue and it will be easier to track.

PS: See (this)[http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git] post to edit incorrect commit message.

**Comment by barbeau** [comment]
Agreed - doing "Fix #X" also automatically closes the issue on Github when the commit is merged - so overall makes our lives easier :).

**Comment by azizmb9494** [comment]
Completed. Thanks @cagryInside, @barbeau!

**Comment by barbeau** [comment]
Thanks @azizmb9494!
