### PR TITLE
Fix #529 - Avoid fragment transaction after onSaveInstanceState

### LINKED ISSUE #529: IllegalStateException: Can not perform this action after onSaveInstanceState
**Summary:** 

From Android Developer Console for staged rollout v2.0.12:

~~~
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at org.onebusaway.android.report.ui.SimpleArrivalListFragment.show(SimpleArrivalListFragment.java:87)
	at org.onebusaway.android.report.ui.InfrastructureIssueActivity.showArrivalListFragment(InfrastructureIssueActivity.java:1055)
	at org.onebusaway.android.report.ui.InfrastructureIssueActivity.showTripProblemFragment(InfrastructureIssueActivity.java:1040)
	at org.onebusaway.android.report.ui.InfrastructureIssueActivity.showTransitService(InfrastructureIssueActivity.java:982)
	at org.onebusaway.android.report.ui.InfrastructureIssueActivity.onSpinnerItemSelected(InfrastructureIssueActivity.java:522)
	at org.onebusaway.android.report.ui.InfrastructureIssueActivity.access$300(InfrastructureIssueActivity.java:78)
	at org.onebusaway.android.report.ui.InfrastructureIssueActivity$2.onItemSelected(InfrastructureIssueActivity.java:457)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:931)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:920)
	at android.widget.AdapterView.-wrap1(AdapterView.java)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:890)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
~~~

There is also a similar stacktrace from a crash in April for the production v1.7.9 - not sure if this is related to the same problem, but both stack traces including the flow for trip problem reporting:

~~~
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1360)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1378)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
	at com.joulespersecond.seattlebusbot.ReportTripProblemFragment.show(ReportTripProblemFragment.java:77)
	at com.joulespersecond.seattlebusbot.ArrivalsListFragment$3.onClick(ArrivalsListFragment.java:436)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:954)
	at android.widget.AdapterView.performItemClick(AdapterView.java:308)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1524)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3531)
	at android.widget.AbsListView$3.run(AbsListView.java:4898)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5586)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
~~~

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

For v2.0.12 crash:

~~~
* Nexus 6P (angler)
* Manufacturer Google 
* Android version Android 6.0 
* RAM (MB) 3072 
* Screen size 1440 × 2560 
* Screen density (dpi) 560 
* OpenGL ES version 3.1 
* Native platform armeabi-v7a 
* CPU make Qualcomm 
* CPU model MSM8994
~~~

for v1.7.9 crash:

~~~
* Galaxy S5 (k3g)
* Manufacturer Samsung 
* Android version Android 4.4 
* RAM (MB) 2048 
* Screen size 1080 × 1920 
* Screen density (dpi) 480 
* OpenGL ES version 3.0 
* Native platform armeabi-v7a 
* CPU make Samsung 
* CPU model Exynos 5422
~~~

@cagryInside Could you please take a look at this?  Thanks!

### PR DESCRIPTION
**Pull request by cagryInside**
Use `try catch` block to catch `IllegalStateException` during fragment commit. If there is `IllegalStateException` occurred, simply do not show the fragment.

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/report/ui/SimpleArrivalListFragment.java [hunk 1]
```diff
@@ -81,10 +82,14 @@ public static void show(AppCompatActivity activity, Integer containerViewId,
...
-        ft.replace(containerViewId, fragment, TAG);
-        ft.addToBackStack(null);
-        ft.commit();
+        try {
+            FragmentTransaction ft = fm.beginTransaction();
+            ft.replace(containerViewId, fragment, TAG);
+            ft.addToBackStack(null);
+            ft.commit();
+        } catch (IllegalStateException e) {
+            Log.v("ArrivalListFragment", "Cannot show SimpleArrivalListFragment");
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/SimpleArrivalListFragment.java]: @cagryInside Could you change this error level logging and move tag to TAG variable?  So:

`Log.e(TAG, "Cannot show SimpleArrivalListFragment");`

...and `TAG` should be declared as `SimpleArrivalListFragment` in the first entry in the Fragment.

Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/SimpleArrivalListFragment.java]: Actually, looks like `TAG` already exists - we should also print more info about the exception - so I think this line should be:

`Log.e(TAG, "Cannot show SimpleArrivalListFragment - " + e.toString());`

Comment (cagryInside) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/SimpleArrivalListFragment.java]: Actually at first I did in that way, but it is giving an error because `SimpleArrivalListFragment` is longer than 23 chars:

screen shot 2016-06-09 at 3 33 14 pm

Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/SimpleArrivalListFragment.java]: Ah - yes, I think that's Lint, I've seen it before.  In that case, just shorten the TAG to be `SimpArrivalListFragment` - I've done that with a few other Fragments/Activities.

Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/report/ui/SimpleArrivalListFragment.java]: And I'd prefer just `TAG`, not the fully qualified `SimpleArrivalListFragment.TAG`.

**Comment by cagryInside** [comment]
@barbeau It should be good now!

**Comment by barbeau** [comment]
Thanks @cagryInside!
