### PR TITLE
Fixed #1187 - Weather Feature Crash

### LINKED ISSUE #1187: Crash in weather feature
I saw this pop up on the console while working on the app.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.onebusaway.android.io.request.weather.models.CurrentForecast.getIcon()' on a null object reference
	at org.onebusaway.android.ui.HomeActivity.setWeatherData(HomeActivity.java:2004)
	at org.onebusaway.android.ui.HomeActivity.onWeatherResponseReceived(HomeActivity.java:2029)
	at org.onebusaway.android.io.request.weather.WeatherRequestTask.onPostExecute(WeatherRequestTask.java:29)
	at org.onebusaway.android.io.request.weather.WeatherRequestTask.onPostExecute(WeatherRequestTask.java:8)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### PR DESCRIPTION
**Pull request by amrhossamdev**
Fixes #1187 

I added extra validation for weather response.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java [hunk 1]
```diff
@@ -1997,14 +1997,25 @@ private void initWeatherView(){
         weatherView = findViewById(R.id.weatherView);
     }
 
-    private void setWeatherData(){
+    private void setWeatherData() {
         TextView tempTxtView = findViewById(R.id.weatherTextView);
         ImageView weatherImageView = findViewById(R.id.weatherStateImageView);
+        String weatherIcon = weatherResponse.getCurrent_forecast().getIcon();
```
Comment (aaronbrethorst) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:2003]: what happens if `getCurrent_forecast()` returns `null`?

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
one question/request for change but otherwise looks great. thanks for turning this around so quickly!

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java (hunk 1 above)
Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:2003]: `getCurrent_forecast()` will not be null I have added validation on line `2040`

`weatherResponse.getCurrent_forecast() != null`

Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:2003]: I can't reproduce the issue but I have added logical changes to avoid this happen

**Review by aaronbrethorst — APPROVED** [review]
great work, thank you!
