### PR TITLE
Fix #480 and #482 - Restore callback methods on orientation change

### LINKED ISSUE #480: Route favorite dialog crashes upon orientation change
**Summary:** 

Reported via Android Developer Console:

~~~
java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.ui.RouteFavoriteDialogFragment$Callback.onSelectionComplete(boolean)' on a null object reference
	at org.onebusaway.android.ui.RouteFavoriteDialogFragment$1.onClick(RouteFavoriteDialogFragment.java:207)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
~~~

**Steps to reproduce:** 

I was able to reproduce by doing the following:

1. Open any stop
2. Tap on any arrival
3. Select "Add star to route"
4. Rotate the screen
5. Tap on "Save"

**Expected behavior:** 

The app should complete the rotation and allow the user to save the favorite route.

**Observed behavior:** 

The app crashes with the above stacktrace.

**Device and Android version:** 

I reproduced this on a stock LG G4 with Android 6.0

### PR DESCRIPTION
**Pull request by cagryInside**
This PR fixes two issues (Issue https://github.com/OneBusAway/onebusaway-android/issues/480, Issue https://github.com/OneBusAway/onebusaway-android/issues/482).

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java [hunk 1]
```diff
@@ -268,6 +269,23 @@ public View onCreateView(LayoutInflater inflater,
     }
 
     @Override
+    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
+        RouteFavoriteDialogFragment dialogFragment = (RouteFavoriteDialogFragment)
+                getFragmentManager().findFragmentByTag(RouteFavoriteDialogFragment.TAG);
+        if (dialogFragment != null) {
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java]: Could you put the code that's a duplicate of lines 721-728 (setting the callback) in a method, and call that method from both locations?  I could see having the duplicate code causing headaches down the road, of someone changing the code in lines 721-728 and then trying to figure out why the behavior isn't changing.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java [hunk 2]
```diff
@@ -268,6 +269,23 @@ public View onCreateView(LayoutInflater inflater,
     }
 
     @Override
+    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java]: Could you please add a comment here saying why this is added, and reference the issue number?  Something like "This is required to avoid an NPE when the user rotates their phone while setting a route favorite - see #480".

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java [hunk 3]
```diff
@@ -268,6 +269,23 @@ public View onCreateView(LayoutInflater inflater,
...
+            dialogFragment.setCallback(new RouteFavoriteDialogFragment.Callback() {
+                @Override
+                public void onSelectionComplete(boolean savedFavorite) {
+                    if (savedFavorite) {
+                        refreshLocal();
+                    }
+                }
+            });
+        }
+        super.onViewStateRestored(savedInstanceState);
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java]: Seems like the call to `super.onViewStateRestored(savedInstanceState)` might be better as the first line of this method?  In other words, the super implementation should be called before our code?  Not sure about this.

**Comment by barbeau** [comment]
Thanks @cagryInside, looks pretty good.  A few inline comments on the route favorites commit.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java (hunk 3 above)
Comment (cagryInside) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/ArrivalsListFragment.java]: I did a little bit google search on it. Seems most people prefer to call first the super class then run their code. However there is no official recommendation exist for this.

PS: Example google fragment code calls the super class first. http://developer.android.com/reference/android/app/Fragment.html

Therefore, I am going to move `super.onViewStateRestored(savedInstanceState);` to the beginning.

**Comment by cagryInside** [comment]
> Thanks @cagryInside, looks pretty good. A few inline comments on the route favorites commit.

Latest commits fixes inline comments.

**Comment by barbeau** [comment]
@cagryInside Thanks!  Also, could you please rebase this on master?  Looks like there are conflicts now.

**Comment by cagryInside** [comment]
> @cagryInside Thanks! Also, could you please rebase this on master? Looks like there are conflicts now.

I should be good now.

**Comment by barbeau** [comment]
Thanks @cagryInside, looks good!
