### PR TITLE
Fix #517 - Restore zoom level and location on orientation change in route map view

### LINKED ISSUE #517: Map doesn't zoom to route on orientation change if sliding panel closed
**Summary:** 

If you rotate your device when showing a route on the map and the sliding panel is closed, the map will center on lat/long (0,0) and will not zoom to show the route.

Note that if the sliding panel is showing, it does zoom correctly.

**Steps to reproduce:** 

1. Tap on a stop on the map in portrait orientation
1. Tap on an arrival time, and choose "Show route on map"
1. Close the sliding panel by hitting the Back button
1. Rotate the device to landscape orientation

**Expected behavior:** 

Zoom to show me the route on the map:

image

**Observed behavior:** 

A blue screen in the map area, which is the view of the ocean at lat/long (0,0):

image

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Screenshots:** 

See above

### PR DESCRIPTION
**Pull request by cagryInside**
This pr fixes the map restore problem on orientation change in `RouteMapController`.

Results:

device-2016-06-16-002114
device-2016-06-16-002221

device-2016-06-16-002645
device-2016-06-16-002719

**P.S.:** This PR requires the `BaseMapFragment` to set `mFocusStopId` to `null` when the stop focus is gone. This development has already been done in this PR https://github.com/OneBusAway/onebusaway-android/pull/463. Therefore, I need to rebase this PR on top of the master branch after the PR https://github.com/OneBusAway/onebusaway-android/pull/463 is merged.

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @cagryInside!  #463 is now merged, so feel free to rebase.

**Comment by cagryInside** [comment]
> Thanks @cagryInside! #463 is now merged, so feel free to rebase.

Thanks @barbeau, it should be good now.

File: onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java [hunk 1]
```diff
@@ -211,6 +212,33 @@ public void onSaveInstanceState(Bundle outState) {
         outState.putString(MapParams.ROUTE_ID, mRouteId);
         outState.putBoolean(MapParams.ZOOM_TO_ROUTE, mZoomToRoute);
         outState.putBoolean(MapParams.ZOOM_INCLUDE_CLOSEST_VEHICLE, mZoomIncludeClosestVehicle);
+
+        Location centerLocation = mFragment.getMapView().getMapCenterAsLocation();
+        outState.putDouble(MapParams.CENTER_LAT, centerLocation.getLatitude());
+        outState.putDouble(MapParams.CENTER_LON, centerLocation.getLongitude());
+        outState.putFloat(MapParams.ZOOM, mFragment.getMapView().getZoomLevelAsFloat());
+        Log.v("save zoomlevel", mFragment.getMapView().getZoomLevelAsFloat() + "");
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java]: Let's delete this Log statement - seems only useful in debugging to make sure this implementation works correctly.

File: onebusaway-android/src/main/java/org/onebusaway/android/map/StopMapController.java [hunk 2]
```diff
@@ -245,6 +245,11 @@ public void onSaveInstanceState(Bundle outState) {
     }
 
     @Override
+    public void onViewStateRestored(Bundle savedInstanceState) {
+
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/StopMapController.java]: Can you add a brief comment here on why we don't need to do anything in onViewStateRestored() for the StopMapController?

**Comment by barbeau** [comment]
After installing the current master branch on my device, and then installing this PR, I get a crash on startup every time and see the following stack trace:

~~~
AndroidRuntime: FATAL EXCEPTION: main
	   Process: com.joulespersecond.seattlebusbot, PID: 11148
	   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.map.MapModeController.onViewStateRestored(android.os.Bundle)' on a null object reference
		   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
		   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
		   at android.app.ActivityThread.access$900(ActivityThread.java:157)
		   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
		   at android.os.Handler.dispatchMessage(Handler.java:102)
		   at android.os.Looper.loop(Looper.java:148)
		   at android.app.ActivityThread.main(ActivityThread.java:5525)
		   at java.lang.reflect.Method.invoke(Native Method)
		   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
		   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
		Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.map.MapModeController.onViewStateRestored(android.os.Bundle)' on a null object reference
		   at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onViewStateRestored(BaseMapFragment.java:338)
		   at android.support.v4.app.Fragment.restoreViewState(Fragment.java:469)
		   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
		   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
		   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
		   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
		   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
		   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
		   at org.onebusaway.android.ui.HomeActivity.onStart(HomeActivity.java:332)
		   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
		   at android.app.Activity.performStart(Activity.java:6288)
		   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
		   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
		   at android.app.ActivityThread.access$900(ActivityThread.java:157) 
		   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
		   at android.os.Handler.dispatchMessage(Handler.java:102) 
		   at android.os.Looper.loop(Looper.java:148) 
		   at android.app.ActivityThread.main(ActivityThread.java:5525) 
		   at java.lang.reflect.Method.invoke(Native Method) 
		   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
		   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
~~~

I believe prior to installing this I just had a normal `HomeActivity` open and was looking at the stops on the map (i.e., did not have route mode open).

**Comment by barbeau** [comment]
I had the `obaAmazonDebug` build variant selected in Android Studio, running on a LG G4 (which is wrong) when I got the above stack trace, but just tried again with normal `obaGoogleDebug` variant and got the same stack trace:

~~~
 E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.joulespersecond.seattlebusbot, PID: 17729
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.map.MapModeController.onViewStateRestored(android.os.Bundle)' on a null object reference
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
	   at android.app.ActivityThread.access$900(ActivityThread.java:157)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
	   at android.os.Handler.dispatchMessage(Handler.java:102)
	   at android.os.Looper.loop(Looper.java:148)
	   at android.app.ActivityThread.main(ActivityThread.java:5525)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
	Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.map.MapModeController.onViewStateRestored(android.os.Bundle)' on a null object reference
	   at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onViewStateRestored(BaseMapFragment.java:338)
	   at android.support.v4.app.Fragment.restoreViewState(Fragment.java:469)
	   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
	   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
	   at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
	   at org.onebusaway.android.ui.HomeActivity.onStart(HomeActivity.java:332)
	   at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
	   at android.app.Activity.performStart(Activity.java:6288)
	   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
	   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
	   at android.app.ActivityThread.access$900(ActivityThread.java:157) 
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
	   at android.os.Handler.dispatchMessage(Handler.java:102) 
	   at android.os.Looper.loop(Looper.java:148) 
	   at android.app.ActivityThread.main(ActivityThread.java:5525) 
	   at java.lang.reflect.Method.invoke(Native Method) 
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
~~~

File: onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java [hunk 3]
```diff
@@ -211,6 +212,33 @@ public void onSaveInstanceState(Bundle outState) {
...
+            // let the BaseMapFragment to handle map state with focused stop
+
+            float mapZoom = savedInstanceState.getFloat(MapParams.ZOOM, MapParams.DEFAULT_ZOOM);
+            if (mapZoom != MapParams.DEFAULT_ZOOM) {
+                mFragment.getMapView().setZoom(mapZoom);
+            }
+
+            double lat = savedInstanceState.getDouble(MapParams.CENTER_LAT);
+            double lon = savedInstanceState.getDouble(MapParams.CENTER_LON);
+            if (lat != 0d && lon != 0d) {
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java]: This should probably be:

`if (lat != 0.0d && lon != 0.0d) {`

Android docs for Bundle say:

>Returns the value associated with the given key, or 0.0 if no mapping of the desired type exists for the given key.

They should be equivalent, but just to be sure... :)

File: onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java [hunk 4]
```diff
@@ -211,6 +212,33 @@ public void onSaveInstanceState(Bundle outState) {
...
+                Location location = LocationUtils.makeLocation(lat, lon);
+                mFragment.getMapView().setMapCenter(location, true, false);
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java]: I can't test this yet because of the NPE I commented on, but I'm thinking this should probably be:

`mFragment.getMapView().setMapCenter(location, false, false);`

...so the map snaps to the location, rather than animates to it.  Are we currently animating from 0.0 to this lat/long, or from a nearby lat/long to this lat/long?

**Comment by barbeau** [comment]
Thanks @cagryInside!  A few comments in-line and the NPE above.

File: onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java (hunk 1 above)
Comment (cagryInside) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java]: Yeah sorry, It was for debugging purposes, I forgot.

**Comment by cagryInside** [comment]
> After installing the current master branch on my device, and then installing this PR, I get a crash on startup every time and see the following stack trace:
> 
> AndroidRuntime: FATAL EXCEPTION: main
>        Process: com.joulespersecond.seattlebusbot, PID: 11148
>        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.map.MapModeController.onViewStateRestored(android.os.Bundle)' on a null object reference
>            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
>            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
>            at android.app.ActivityThread.access$900(ActivityThread.java:157)
>            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
>            at android.os.Handler.dispatchMessage(Handler.java:102)
>            at android.os.Looper.loop(Looper.java:148)
>            at android.app.ActivityThread.main(ActivityThread.java:5525)
>            at java.lang.reflect.Method.invoke(Native Method)
>            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
>            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
>         Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.map.MapModeController.onViewStateRestored(android.os.Bundle)' on a null object reference
>            at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onViewStateRestored(BaseMapFragment.java:338)
>            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:469)
>            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
>            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
>            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
>            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
>            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
>            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
>            at org.onebusaway.android.ui.HomeActivity.onStart(HomeActivity.java:332)
>            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
>            at android.app.Activity.performStart(Activity.java:6288)
>            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
>            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
>            at android.app.ActivityThread.access$900(ActivityThread.java:157) 
>            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
>            at android.os.Handler.dispatchMessage(Handler.java:102) 
>            at android.os.Looper.loop(Looper.java:148) 
>            at android.app.ActivityThread.main(ActivityThread.java:5525) 
>            at java.lang.reflect.Method.invoke(Native Method) 
>            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
>            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

IMO this errors are not related to this development. They might occur because of the Android Studio's hot-swap feature. Logs show that the crash happened at `(BaseMapFragment.java:338)`. However, there is nothing exist related to NPE in that line.

**Comment by cagryInside** [comment]
@barbeau I just pushed another commit that fixes the inline comments.

**Comment by barbeau** [comment]
Agreed, I think the NPE was related to Android Studio hot swap error - I couldn't reproduce this again after starting with a clean build.

File: onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java (hunk 4 above)
Comment (cagryInside) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java]: > I can't test this yet because of the NPE I commented on, but I'm thinking this should probably be:
> 
> mFragment.getMapView().setMapCenter(location, false, false);
> 
> ...so the map snaps to the location, rather than animates to it. Are we currently animating from 0.0 to this lat/long, or from a nearby lat/long to this lat/long?

I fixed this by using `mFragment.getMapView().setMapCenter(location, false, false);` . However, this only disables the animation when the sliding panel is not open. When it is visible, `HomeActivity` handles the orientation changes by calling `onArrivalTimesUpdated`:

```
public void onArrivalTimesUpdated(ObaArrivalInfoResponse response) {
        if (response == null || response.getStop() == null) {
            return;
        }

        // If we're missing any local references (e.g., if orientation just changed), store the values
        if (mFocusedStopId == null) {
            mFocusedStopId = response.getStop().getId();
        }
        if (mFocusedStop == null) {
            mFocusedStop = response.getStop();

            // Since mFocusedStop was null, the layout changed, and we should recenter map on stop
            if (mMapFragment != null && mSlidingPanel != null) {
                mMapFragment.setMapCenter(mFocusedStop.getLocation(), true,
                        mSlidingPanel.getPanelState() == SlidingUpPanelLayout.PanelState.ANCHORED);
            }

            // ...and we should add a focus marker for this stop
            if (mMapFragment != null) {
                mMapFragment.setFocusStop(mFocusedStop, response.getRoutes());
            }
        }

        // Header might have changed height, so make sure my location button is set above the header
        moveMyLocationButton();

        // Show arrival info related tutorials
        showArrivalInfoTutorials(response);
    }

```

And, this method animates the map. Therefor there is an inconsistency on rotation in `RouteMapController`. Map doesn't animate if the sliding panel is not open, but it animates when the panel is open.

Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/map/RouteMapController.java]: Yes, we should change this to not animate as well - could you change this to `false` and push as a new commit in this PR, and reference this comment from it?  This way we keep behavior consistent.

**Comment by barbeau** [comment]
Repeating this here, because Github hid the other comment:

>Yes, we should change `HomeActivity.onArrivalTimesUpdated()` to not animate as well - could you change this to false and push as a new commit in this PR, and reference this comment from it? This way we keep behavior consistent.

**Comment by cagryInside** [comment]
> Yes, we should change this to not animate as well - could you change this to false and push as a new commit in this PR, and reference this comment from it? This way we keep behavior consistent.

@barbeau I disabled the animation and tested the development. It should be good now.

**Comment by barbeau** [comment]
Thanks @cagryInside!
