### PR TITLE
Fixed #1157 - Dialog crash

### LINKED ISSUE #1157: Crashes on clicking temporary detour
**Summary:** 

App crashes on clicking temporary detour. Refer to the screenshot below for clear understanding.

**Steps to reproduce:** 

Select any stop which shows arrivals list. Click on temporary detour.

**Device and Android version:** 

Asus Zenfone Max pro M1, Android Pie
Pixel 7 pro API 34

**Screenshots:** 

IMG_20240310_122750_550~2

### PR DESCRIPTION
**Pull request by amrhossamdev**
Fixes #1157.

We need to check if the alert has a null description, also I have updated the naming convention because it was very confusing.

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java [hunk 1]
```diff
@@ -162,10 +162,12 @@ public void onClick(DialogInterface dialog, int which) {
...
         title.setText(args.getString(TITLE));
 
-        TextView desc = (TextView) dialog.findViewById(R.id.alert_description);
+        TextView descTxtView = (TextView) dialog.findViewById(R.id.alert_description);
 
-        if (desc != null) {
-            desc.setText(Html.fromHtml(args.getString(DESCRIPTION)));
+        String desc = args.getString(DESCRIPTION);
+
+        if (descTxtView != null &&!TextUtils.isEmpty(desc)) {
```
Comment (aaronbrethorst) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java:169]: please be sure to watch your formatting on lines like this. I'd prefer to see this as:

```
if (descTxtView != null && !TextUtils.isEmpty(desc)) {
```

**Review by aaronbrethorst — APPROVED** [review]
looks good! one more quibble about formatting, but no reason to block merging for that. thanks for tackling this.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java (hunk 1 above)
Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java:169]: Thank you for correcting me, it's more clear now!
