### PR TITLE
Fix #544: Tapping on vehicle marker popup focuses on vehicle icon in TripDetailsListFragment.

### LINKED ISSUE #544: Tapping on vehicle marker popup should focus on vehicle icon in TripDetailsListFragment
**Summary:** 

Currently, if a user taps on an arrival time at a particular stop, the stop and vehicle icons both appear in TripDetailsListFragment and the stop is focused as the top visible record in the list - this is the desired behavior:

image

Prior to #463, we weren't showing the bus stop icon in TripDetailsListFragment if the user tapped on the vehicle marker popup balloon to enter TripDetailsListFragment.  In that case, the vehicle icon would take focus and appear as the first visible row in TripDetailsListFragment:

image

This is the desired behavior in terms of focusing on the vehicle as the first record, but the stop icon for the user's currently focused stop on the map was absent.  #463 fixes this to include the stop icon as well as the vehicle icon - however, a side effect of this is that if the stop icon is included, we always focus on the stop icon, and not the vehicle icon.  This isn't a problem with #463, but just an unintended consequence of the current code that sets the top visible list item, which always defaults to focusing on the stop if it's included.

IMO the behavior should be that if the user tapped on the vehicle marker popup balloon, we should focus on that vehicle as the first record (i.e., the same behavior prior to #463).

A fix for this is to allow the calling Activity to specify via Intent parameters whether the stop or vehicle should have focus as the first record.  If coming from ArrivalsListFragment and the user tapped on an arrival time, then use the Intent to set focus to the stop n TripDetailsListFragment.  If coming from the VehicleOverlay when a user tapped on the vehicle marker popup, then use the Intent to set focus to the vehicle in TripDetailsListFragment.

**Steps to reproduce:** 

1. Show a route
1. Tap on a vehicle marker
1. Tap on the vehicle marker balloon popup

**Expected behavior:** 

The vehicle icon should be the record at the top of the visible portion of the list:

image

**Observed behavior:** 

The stop icon is the record at the top of the visible portion of the list:

image

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Screenshots:** 

See above

### PR DESCRIPTION
**Pull request by azizmb9494**
If a vehicle marker popup is tapped, it attempts to focus on the stop with the bus icon first. If stop marker is selected, it attempts to focus on that selected stop.

Testing Done:
1. Selected stop, tapped "Show Route on Map", clicked vehicle overlay and tapped popup. Trip Details Activity opened with bus focused. Worked as wanted.
2. Selected stop, tapped "View Trip Details". Trip Details Activity opened with stop focused. Worked as wanted.
3. gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest: Success.

### CODE REVIEW

File: onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/VehicleOverlay.java [hunk 1]
```diff
@@ -300,9 +300,10 @@ public void onInfoWindowClick(Marker marker) {
         ObaTripStatus status = mMarkerData.getStatusFromMarker(marker);
 
         if (mController != null && mController.getFocusedStopId() != null) {
-            TripDetailsActivity.start(mActivity, status.getActiveTripId(), mController.getFocusedStopId());
+            TripDetailsActivity.start(mActivity, status.getActiveTripId(),
+                    mController.getFocusedStopId(), "vehicle");
```
Comment (barbeau) [inline onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/VehicleOverlay.java]: "vehicle" string should be moved to a constant `SCROLL_MODE_VEHICLE` in `TripDetailsListFragment`.

File: onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/VehicleOverlay.java [hunk 2]
```diff
@@ -300,9 +300,10 @@ public void onInfoWindowClick(Marker marker) {
...
         } else {
-            TripDetailsActivity.start(mActivity, status.getActiveTripId());
+            TripDetailsActivity.start(mActivity, status.getActiveTripId(), null, "vehicle");
```
Comment (barbeau) [inline onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/VehicleOverlay.java]: I'd prefer creating a new overloaded `TripDetailsActivity.start()` method without stopId so we don't have to pass in `null` here.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripDetailsListFragment.java [hunk 3]
```diff
@@ -26,6 +26,7 @@
 import org.onebusaway.android.io.elements.ObaTripStatus;
 import org.onebusaway.android.io.request.ObaTripDetailsRequest;
 import org.onebusaway.android.io.request.ObaTripDetailsResponse;
+import org.onebusaway.android.tripservice.BootstrapService;
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripDetailsListFragment.java]: Looks like this import can be removed - in Android Studio, when committing you can check "Optimize imports" to do this automatically.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripDetailsListFragment.java [hunk 4]
```diff
@@ -228,19 +234,8 @@ private void setTripDetails(ObaTripDetailsResponse data) {
...
-                    listView.post(new Runnable() {
-                        @Override
-                        public void run() {
-                            listView.setSelection(mStopIndex);
-                        }
-                    });
-                }
-            } else {
-                // If we don't have a stop, then scroll to the current position of the bus
+            if (mScrollMode != null && mScrollMode.equals("vehicle")) {
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripDetailsListFragment.java]: To simplify this section of code, this can be:

~~~
if (mScrollMode == null) {
    // Don't automatically scroll to stop or vehicle icon
    return;
}
~~~

So, if no scroll mode is provided, we do nothing.  And then do a `switch` for the two scroll modes.  This `switch` should probably be in it's own private method to avoid cluttering this one too much.

**Comment by barbeau** [comment]
Thanks @azizmb9494!  This generally looks good, a few comments inline.

File: onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/VehicleOverlay.java (hunk 1 above)
Comment (barbeau) [inline onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/VehicleOverlay.java]: We'll also need to add a `SCROLL_MODE_STOP` in `TripDetailsListFragment`, and in `ArrivalsListFragment.goToTripDetails()` set the stop mode.

**Comment by azizmb9494** [comment]
Thanks @barbeau, fixed!

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripDetailsListFragment.java [hunk 5]
```diff
@@ -704,4 +689,65 @@ public Integer getNextStopIndex() {
...
+                    if (mStopIndex != null) {
+                        listView.post(new Runnable() {
+                            @Override
+                            public void run() {
+                                listView.setSelection(mStopIndex);
+                            }
+                        });
+                    }
+                }
+            }
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripDetailsListFragment.java]: I think you're missing a `break` here - testing the PR w/ breakpoints it seems to execute both `case` blocks.

**Comment by barbeau** [comment]
@azizmb9494 Sorry it's taken so long to review!.  Looks good in general, but I believe there is a missing `break` statement (see in-line comment), other than that it looks good.  If you can tweak that we can get this merged!

**Comment by azizmb9494** [comment]
No worries, fixed @barbeau

**Comment by barbeau** [comment]
Thanks @azizmb9494, looks good!
