### PR TITLE
fixed #981

### LINKED ISSUE #981: Trip planning - Allow planning from contact address
**Summary:** 

User request:

>When selecting a destination or a starting point for my trip please allow it to access my contacts on my Android device

**Steps to reproduce:** 

1. Plan a trip and tap on origin or destination box

**Expected behavior:** 

Give me an option to select a contact address at the origin or destination

**Observed behavior:** 

Only option is to type an address (workaround: copy address from contact and paste into origin/destination box)

**Device and Android version:** 

N/A

### PR DESCRIPTION
**Pull request by viditpawar0**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

Fixed #981 

Summary of changes: -
- Implemented a `mSelectAddressFromContactLauncher` in `TripPlanFragment` that can be used to get the user select a contact and set the address from the contact to the text field.
- Added a contact selector icon for both addresses in the `fragment_trip_plan.xml`.

Screenshots of UI Changes: -
Screenshot_20241212_210844_OneBusAway

### CODE REVIEW

**Comment by viditpawar0** [comment]
@aaronbrethorst I have signed the CLA, still it says that it is pending

**Comment by aaronbrethorst** [comment]
@viditpawar0 I don't know why it says you haven't signed it, but I do see that you have completed it from the admin console. fyi @amrhossamdev

**Comment by amrhossamdev** [comment]
Hi @viditpawar0 

Thank you for your contribution. I will test that and get back to you!

**Comment by amrhossamdev** [comment]
Hi @viditpawar0, thank you for your contribution! I have tested the functionality, and it works perfectly. I will request code changes from you, and it will be ready for merging.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java [hunk 1]
```diff
@@ -127,6 +136,45 @@ interface Listener {
 
     private FirebaseAnalytics mFirebaseAnalytics;
 
+    //sets the address in the text view from the user selected contact
+    private final String ID = "id";
+    private ActivityResultLauncher<TextView> mSelectAddressFromContactLauncher = registerForActivityResult(
+            new ActivityResultContract<TextView, Intent>() {
+                int tvId;
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java:143]: Just a quick thought when it comes to naming, think about how it might feel to read this code a couple of years down the line. Would `tvId` instantly make sense? Something like `addressInputId` could make it much clearer and easier to follow.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java [hunk 2]
```diff
@@ -127,6 +136,45 @@ interface Listener {
...
+                    return null;
+                }
+            },
+            addressIntent -> {
+                if (addressIntent == null) {
+                    return;
+                }
+                Uri addressUri = addressIntent.getData();
+                String[] projection = new String[]{ContactsContract.CommonDataKinds.StructuredPostal.FORMATTED_ADDRESS};
+                Cursor cursor = getContext().getContentResolver().query(addressUri, projection, null, null, null);
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java:168]: The Cursor is not being closed, which can lead to memory leaks. Always close the Cursor in a finally block or use a try-with-resources statement.
```Java
try (Cursor cursor = getContext().getContentResolver().query(addressUri, projection, null, null, null)) {
    if (cursor != null && cursor.moveToFirst()) {
        int addressIndex = cursor.getColumnIndex(ContactsContract.CommonDataKinds.StructuredPostal.FORMATTED_ADDRESS);
        String address = cursor.getString(addressIndex).replace("\n", ", ");
        TextView tv = getActivity().findViewById(addressIntent.getIntExtra(ID, -1));
        tv.post(() -> tv.setText(address));
    }
}

```

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java [hunk 3]
```diff
@@ -127,6 +136,45 @@ interface Listener {
 
     private FirebaseAnalytics mFirebaseAnalytics;
 
+    //sets the address in the text view from the user selected contact
+    private final String ID = "id";
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java:140]: The variable can be renamed to `addressInputIdKey` and used as a constant.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java [hunk 4]
```diff
@@ -127,6 +136,45 @@ interface Listener {
...
+    private ActivityResultLauncher<TextView> mSelectAddressFromContactLauncher = registerForActivityResult(
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripPlanFragment.java:141]: You can separate `ActivityResultContract` and `ActivityResultLauncher` as two classes for better readability also it can be like this:

```Java
private final ActivityResultContract<TextView, Intent> selectAddressFromContactContract = new ActivityResultContract<TextView, Intent>() {
    private int addressInputId;

    @NonNull
    @Override
    public Intent createIntent(@NonNull Context context, TextView textView) {
        Intent intent = new Intent(Intent.ACTION_PICK);
        intent.setType(ContactsContract.CommonDataKinds.StructuredPostal.CONTENT_TYPE);
        addressInputId = textView.getId();
        return intent;
    }

    @Override
    public Intent parseResult(int resultCode, @Nullable Intent intent) {
        if (intent != null) {
            return intent.putExtra(ID, tvId);
        }
        return null;
    }
};

private final ActivityResultLauncher<TextView> mSelectAddressFromContactLauncher = registerForActivityResult(
        selectAddressFromContactContract,
        addressIntent -> {
            if (addressIntent == null) {
                return;
            }
            Uri addressUri = addressIntent.getData();
            String[] projection = new String[]{FORMATTED_ADDRESS};
            try (Cursor cursor = getContext().getContentResolver().query(addressUri, projection, null, null, null)) {
                if (cursor != null && cursor.moveToFirst()) {
                    int addressIndex = cursor.getColumnIndex(ContactsContract.CommonDataKinds.StructuredPostal.FORMATTED_ADDRESS);
                    String address = cursor.getString(addressIndex).replace("\n", ", ");
                    TextView addressInputId = getActivity().findViewById(addressIntent.getIntExtra(ID, -1));
                    addressInputId.post(() -> tv.setText(address));
                }
            }
        }
);
```

**Review by amrhossamdev — CHANGES_REQUESTED** [review]

**Comment by viditpawar0** [comment]
Thank you so much @amrhossamdev for taking time to review my code and provide insights. I have made the necessary changes. The reason I referred to the address text view in the `mSelectAddressFromContactLauncher` as a text view and not address input is because the `mSelectAddressFromContactLauncher` is able to update any `TextView` with the user selected contact's address. But you are right. Naming should be based on purpose and not ability.

**Comment by amrhossamdev** [comment]
Great job, @viditpawar0! Your work is fantastic! I did notice a small bug: when I select an address for the "starting address" from my contacts, it works perfectly, and the address is set correctly. However, when I select an address for the "ending address," it removes the "starting address" from the input field. And vice versa. Could you please take a look at this? Let me know if you need any assistance!

**Comment by viditpawar0** [comment]
Sure @amrhossamdev , that bug is solved in this commit.

**Comment by amrhossamdev** [comment]
Well done, @viditpawar0. Another thing: you should request to submit to plan the trip after selecting the `to` address. It will be much better for user experience.

**Comment by viditpawar0** [comment]
Okay, @amrhossamdev  I will need a little assistance on that, do I need to call the `checkRequestAndSubmit()` method to submit to plan the trip?

**Comment by amrhossamdev** [comment]
@viditpawar0 Yes, and we need to make sure that we have the `from` and `to` locations to submit a request.

**Comment by viditpawar0** [comment]
@amrhossamdev I will need the api.geocode.earth API to test that which is not working on my device.

Here is the error:
image

Here is the http response:
`{
  "meta": {
    "version": 1,
    "status_code": 401
  },
  "results": {
    "error": {
      "type": "KeyError",
      "message": "No api_key specified."
    }
  }
}`

This is happening while using the `Geocoder` to get the list of  addresses from the address string. It says that no api key is specified. Do I need to set up my own api key for that?

Please help me with this.

**Comment by amrhossamdev** [comment]
@viditpawar0 Can you push your changes?

**Comment by viditpawar0** [comment]
@amrhossamdev sure.

**Comment by viditpawar0** [comment]
@amrhossamdev There you go. But note that this change is un-tested because the geocode api is not working on my device

**Comment by amrhossamdev** [comment]
Thanks, @viditpawar0 I will test that!

**Comment by viditpawar0** [comment]
Welcome, @amrhossamdev !

**Comment by amrhossamdev** [comment]
Great work, @viditpawar0 ! :partying_face:  I made a couple of minor changes. When we select an address from the contacts, we will request `focus` to allow autocomplete suggestions for the address. This is essential to correctly obtain the `latitude` and `longitude`, which are necessary for the trip planning request. This ensures we have the precise location rather than just the address, and that's how trip planning works.

Additionally, I have fixed some minor bugs in the trip planning UI.

image

Overall, fantastic job, and thank you for your contribution! This pull request is ready to merge.

**Comment by viditpawar0** [comment]
@amrhossamdev awesome🤩! I'm excited.

**Comment by amrhossamdev** [comment]
Hi @viditpawar0, could you ensure you signed the `CLA` to merge?

**Comment by viditpawar0** [comment]
@amrhossamdev sure, done. Signed CLA from both accounts

**Review by amrhossamdev — APPROVED** [review]

**Comment by amrhossamdev** [comment]
LGTM, well done 🫡
