### PR TITLE
FIx: Floating Action Button (FAB) Missing Accessible Label

### LINKED ISSUE #1352: Missing Label for Floating Action Button (FAB)
#### **Description:**
The Floating Action Button (FAB) highlighted in the screenshot does not have a label that is readable by screen readers. This impacts accessibility and may prevent visually impaired users from understanding the purpose of the button.
Use Tampa Bay Location

#### **Steps to Reproduce:**
1. Open the app and navigate to the screen containing the FAB.
2. Use an accessibility scanner or TalkBack to check the label for the FAB.
3. Notice that the button lacks a readable label.

#### **Expected Behavior:**
- The FAB should have a content description or label to inform users about its functionality.

#### **Screenshot.**

Image

### PR DESCRIPTION
**Pull request by Avinash-Codes**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

fixes #1352 

https://github.com/user-attachments/assets/2797e31c-546c-4505-85a4-d45cdaf80774

### CODE REVIEW

**Comment by Avinash-Codes** [comment]
@amrhossamdev Ready for review 😃

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java [hunk 1]
```diff
@@ -1714,17 +1714,26 @@ private void setupGooglePlayServices() {
...
+        mLayersFab.setContentDescription(getString(R.string.map_option_layers));
+
         mLayersFab.setButtonIconResource(R.drawable.ic_layers_white_24dp);
         mLayersFab.setButtonBackgroundColour(ContextCompat.getColor(this, R.color.theme_accent));
 
         // Find and set content description on the card view (the actual clickable element)
         View fabCard = mLayersFab.findViewById(R.id.fab_card);
 
+        // Find and set content description on the card view (the actual clickable element)
+        View fabCard = mLayersFab.findViewById(R.id.fab_card);
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:1731]: Please check build errors here.

**Review by amrhossamdev — CHANGES_REQUESTED** [review]
Well done please check my comments and please rebase against main.

**Comment by Avinash-Codes** [comment]
> Well done please check my comments and please rebase against main.

Done @amrhossamdev

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java [hunk 2]
```diff
@@ -1756,8 +1764,18 @@ public void onDeactivateLayer(LayerInfo layer) {
                     }
                 });
         mLayersFab.setOnSpeedDialMenuCloseListener(
-                v -> mLayersFab.setButtonIconResource(R.drawable.ic_layers_white_24dp));
+                v -> {
+                    mLayersFab.setButtonIconResource(R.drawable.ic_layers_white_24dp);
+                    // Reset content description to default state
+                    mLayersFab.setContentDescription(getString(R.string.map_option_layers));
+                    if (fabCard != null) {
+                        fabCard.setContentDescription(getString(R.string.map_option_layers));
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:1772]: Why settings content description two times ?

**Review by amrhossamdev — CHANGES_REQUESTED** [review]
Can you please check my comments

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java (hunk 2 above)
Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:1772]: @Avinash-Codes

Comment (Avinash-Codes) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/HomeActivity.java:1772]: @amrhossamdev Sorry for the late reply, my university exams were going on 🥲. But now that they're over, I'll fix it today.

**Comment by Avinash-Codes** [comment]
@amrhossamdev fixed the issue you can review it 😊

**Review by amrhossamdev — APPROVED** [review]
Well done
