### PR TITLE
Fix the notification channel description typo in createNotificationChannels(). Channel3's description is set on channel2. ALSO, Used UTF-8 charset when converting the custom API URL to bytes in reportAnalytics() to avoid charset issues.

### LINKED ISSUE #1407: Notification channel description typo in createNotificationChannels(). Channel3's description is set on channel2
Here, channel3 is created, but the description is set to channel2. That's a typo. So channel3 would have no description, and channel2's description would be overwritten. This would cause the destination alerts notifications to have an incorrect or missing description, and the arrival reminders might show the wrong description.

### PR DESCRIPTION
**Pull request by Das-R10**
1)In the method createNotificationChannels() the original code accidentally set the description for the destination alerts channel (channel3) on channel2. This fix ensures the description is properly assigned to channel3, making the notification channel's purpose clear to users in their device settings.

2)In the reportAnalytics() method, there's a call to digest.update(getCustomApiUrl().getBytes()). Using getBytes() without specifying a charset can lead to inconsistent behavior on different devices. It's better to use StandardCharsets.UTF_8.

Fixes #1407 

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/app/Application.java [hunk 1]
```diff
@@ -614,7 +615,7 @@ private void reportAnalytics() {
             MessageDigest digest = null;
             try {
                 digest = MessageDigest.getInstance("SHA-1");
-                digest.update(getCustomApiUrl().getBytes());
+                digest.update(getCustomApiUrl().getBytes(StandardCharsets.UTF_8));
```
Comment (Das-R10) [inline onebusaway-android/src/main/java/org/onebusaway/android/app/Application.java:618]: Used StandardCharsets.UTF-8 charset when converting the custom API URL to bytes in reportAnalytics() to avoid charset issues. #

Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/app/Application.java:618]: Can you explain possible issues that might happen ?

Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/app/Application.java:618]: @Das-R10

**Comment by amrhossamdev** [comment]
waiting for your replay @Das-R10

**Comment by Das-R10** [comment]
> waiting for your replay @Das-R10

> When we use getBytes() without specifying a charset, it relies on the platform's default charset.This can lead to different hash values when generating analytics data, making it unreliable. That's why I suggested to use UTF-8.

@amrhossamdev

**Review by amrhossamdev — APPROVED** [review]
Well done @Das-R10
