### PR TITLE
Fix #794 - Add "transit only" mode for trip planning

### LINKED ISSUE #794: Trip planning (bikeshare beta) - add "transit only" mode
**Summary:** 

Reported by user for current 2.2.4 bikeshare beta:

>Currently in OBA android, when you want to plan a trip (using beta OTP client), you can notably choose between bikeshare or transit+bikeshare but can't choose transit only (transit+walk), whereas most of the time you need a separate subscription or ticket to be able to use bikeshare, even when you have unlimited access to transit system.
>
>Would it be possible to implement transit only option?
>
>Also, having a way to display current disruptions as in default OTP client would also be nice, at it can have a main impact on transit.

I agree, we should have a transit-only option (which includes bus and rail).

**Steps to reproduce:** 

Plan a trip in an area with bikeshare

**Expected behavior:** 

Allow me to get trips only for transit, without any bikeshare legs

**Observed behavior:** 

There is no way to eliminate bikeshare from a planned trip

**Device and Android version:** 

N/A

@carvalhorr Would you be able to take a look at this?  I'd like to get this into the production release of the app.

### PR DESCRIPTION
**Pull request by carvalhorr**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/directions/util/TripRequestBuilder.java [hunk 1]
```diff
@@ -196,7 +199,7 @@ public TripRequestBuilder setModeSetById(int id) {
     public int getModeSetId() {
         // IF bike mode is selected in the trip plan additional preferences but bikeshare is not enabled use the default mode (TRANSTI)
         if (BIKESHARE_MODE == mModeId && !Application.isBikeshareEnabled()) {
-            return TRANSIT_MODE;
+            return TRANSIT_AND_BIKE_MODE;
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/directions/util/TripRequestBuilder.java]: @carvalhorr It seems here either the comment is wrong or this should be `TRANSIT_MODE`.  Could you please resolve the two so they match?

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/TripModes.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
+package org.onebusaway.android.ui;
+
+import org.onebusaway.android.R;
+import org.onebusaway.android.app.Application;
+
+/**
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/TripModes.java]: Could you please add a short description to this class and remove the "Created by...".  Also please add Apache license header.

**Comment by barbeau** [comment]
Thanks @carvalhorr!  Looks good!
