### PR TITLE
Fix: Corrected back navigation from 'Your Region' to Settings

### LINKED ISSUE #1302: Back Arrow in "Your Region" Screen Navigates to Home Instead of Settings
**Description:**  
When a user navigates to **Settings → Your Region** and then presses the **TopAppBar back arrow button**, the expected behavior is to return to the **Settings screen**. However, the app incorrectly navigates back to the **Home screen** instead.  

**Steps to Reproduce:**  
1. Open the **Settings** screen.  
2. Tap on **Your Region**.  
3. Press the **TopAppBar back arrow** to go back.  
4. Observe that the app navigates to the **Home screen** instead of the **Settings screen**.  

**Expected Behavior:**  
- Pressing the **TopAppBar back arrow** should navigate **back to the Settings screen**, not the Home screen.  

**Actual Behavior:**  
- The app incorrectly navigates to the **Home screen** when pressing the back arrow in the "Your Region" screen.  

**Screenshots/Video:** 

https://github.com/user-attachments/assets/ff053242-7c5b-4de7-b47f-fd8b52ba468c

**Possible Cause:**  
- The **back navigation logic** might be incorrectly directing the user to the **Home screen** instead of the **Settings screen**.  
- The **navigation stack** might not be properly managed when entering "Your Region" from Settings.

### PR DESCRIPTION
**Pull request by Avinash-Codes**
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

fixes #1302 

[Screen_recording_20250212_121528.webm](https://github.com/user-attachments/assets/8a4e14cc-5104-4684-87b2-255ed6fcf58e)

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/RegionsActivity.java [hunk 1]
```diff
@@ -64,9 +64,15 @@ public void onCreate(Bundle savedInstanceState) {
...
+            onBackPressed();
             return true;
         }
-        return false;
+        return super.onOptionsItemSelected(item);
+    }
+
+    @Override
+    public boolean onSupportNavigateUp() {
+        onBackPressed();
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/RegionsActivity.java:75]: here also.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/RegionsActivity.java [hunk 2]
```diff
@@ -64,9 +64,15 @@ public void onCreate(Bundle savedInstanceState) {
     @Override
     public boolean onOptionsItemSelected(MenuItem item) {
         if (item.getItemId() == android.R.id.home) {
-            NavHelp.goHome(this, false);
+            onBackPressed();
```
Comment (amrhossamdev) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/RegionsActivity.java:67]: `onBackPressed` is deprecated use `getOnBackPressedDispatcher().onBackPressed();` instead.

**Review by amrhossamdev — CHANGES_REQUESTED** [review]
Well done, @Avinash-Codes, please take a look at my feedback.

**Comment by Avinash-Codes** [comment]
> Well done, @Avinash-Codes, please take a look at my feedback.

Made the required changes please review it

**Review by amrhossamdev — APPROVED** [review]
Well done @Avinash-Codes :fire:
