### PR TITLE
Fixed #1138 - AboutActivity UI enhancement.

### LINKED ISSUE #1138: Enhancement: "About"Activity layout needs to be enhanced
**Summary:** 

layout of about page is unorganized.

**Steps to reproduce:** 

step-1: open setting
step-2: click on about.

**Expected behavior:** 

Should be in organized manner (material UI).

**Device and Android version:** 

Xiaomi 11i running Android 13 with the latest version of Google Play Services.

**Screenshots:** 
Before:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/259c40f4-5ca2-4852-b3db-d7934fdb9d05

After:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/11ad077c-c393-4379-9846-a6ab53cc586b

I'm Currently working this issue

### PR DESCRIPTION
**Pull request by sebesti0n**
Fixed #1138
Preview:

https://github.com/OneBusAway/onebusaway-android/assets/114914556/38b1dcd1-e286-49ff-9a18-c8d0efe215e4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/AboutActivity.java [hunk 1]
```diff
@@ -65,16 +70,17 @@ protected void onCreate(Bundle savedInstanceState) {
...
                 .append(" (")
                 .append(versionCode)
-                .append(")\n\n");
+                .append(")\n");
 
         // Majority of content from string resource
-        builder.append(getString(R.string.about_text));
-        builder.append("\n\n");
+//        builder.append(getString(R.string.about_text));
+//        builder.append("\n\n");
```
Comment (neeldoshii) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/AboutActivity.java:81]: If not needed, can we remove the comments? @sebesti0n

**Review by neeldoshii — CHANGES_REQUESTED** [review]

**Review by neeldoshii — APPROVED** [review]

**Review by aaronbrethorst — APPROVED** [review]
Generally, I think this looks great, and I appreciate you tackling it. I have a couple minor quibbles with the content layout and text, but I'll follow up with another PR that covers them shortly.

**Comment by aaronbrethorst** [comment]
@sebesti0n fyi - see #1160
