### PR TITLE
Fixed #1116 Situation Dialog Html Parsing 

### LINKED ISSUE #1116: HTML Parsing Issue : Incorrect parsing of HTML tags in Situation Dialog
**Summary:** 

HTML Parsing issue with Situation dialog, need to use a parser to parse HTML tags, I can work on this issue.
**Steps to reproduce:** 

Select any bus stops and open stops list and click on any situation/alert.
**Expected behavior:** 

Showing stop details without HTML tags.
**Observed behavior:** 

No parsing for HTML tags.

**Device and Android version:** 

Stock - Pixel 6A - API 30 

**Screenshots:** 

Screenshot from 2024-02-24 11-10-10

### PR DESCRIPTION
**Pull request by amrhossamdev**
Fixed #1116 

|      |      |
| ---- | ---- |
| Screenshot_1708804337 | Screenshot_1708804437 |

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them for the initial submission of the pull request.  When addressing comments on a pull request, please push a new commit per comment when possible (reviewers will squash and merge using GitHub merge tool)

### CODE REVIEW

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java [hunk 1]
```diff
@@ -154,16 +155,18 @@ public void onClick(DialogInterface dialog, int which) {
                     }
                 });
 
-        final androidx.appcompat.app.AlertDialog dialog = builder.create();
```
Comment (aaronbrethorst) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java:157]: what's the impact of using the built-in AlertDialog instead of the `androidx` version on an older Android device? (e.g. Android 5)

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java [hunk 2]
```diff
@@ -154,16 +155,18 @@ public void onClick(DialogInterface dialog, int which) {
...
 
         // Set the title, description, and URL (if provided)
         TextView title = (TextView) dialog.findViewById(R.id.alert_title);
         title.setText(args.getString(TITLE));
 
         TextView desc = (TextView) dialog.findViewById(R.id.alert_description);
-        desc.setText(args.getString(DESCRIPTION));
 
+        if (desc != null) {
+            desc.setText(Html.fromHtml(args.getString(DESCRIPTION)));
```
Comment (aaronbrethorst) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java:168]: 👍

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
Thank you for your submission! I have one question for you in a review comment, and then please also verify that your changes work as expected for another region that isn't using HTML, like San Diego or Puget Sound.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java (hunk 1 above)
Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java:157]: it's actually android x, i have just imported it in imports line 30

`import androidx.appcompat.app.AlertDialog;`

instead of declaring an object with package name.

Comment (amrhossamdev) [reply onebusaway-android/src/main/java/org/onebusaway/android/ui/SituationDialogFragment.java:157]: Yes, i have tested it with non html tags strings & also for hyberlinks and it works fine.
Screenshot from 2024-02-25 02-37-59

**Review by aaronbrethorst — APPROVED** [review]
looks great, thank you so much!
