### PR TITLE
Fix #765 - Allow sorting reminders by departure time

### LINKED ISSUE #765: Allow sorting My Reminders by departure time
**Summary:** 

Requested by a user:

>Allow My Reminders to be sorted by departure time.

**Steps to reproduce:** 

1. Go to main nav drawer and select "My reminders"

**Expected behavior:** 

Allow me to sort the reminders, specifically by departure time

**Observed behavior:** 

You can't sort the reminders

**Device and Android version:** 

N/A

### PR DESCRIPTION
**Pull request by hayato1234**
I worked on this (#765 ) issue. I tried to use a similar style as sorting starred stops.
----------------

**before**
It was only sorted by the name of a reminder.

**proposed**
It allows users to switch between "sort by name" and "sort by time"

let me know if there are things that need to be changed. Thank you!

-----------------

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `gradlew connectedObaGoogleDebugAndroidTest connectedObaAmazonDebugAndroidTest` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @hayato1234! Don't worry about the Travis build failure, that was my mistake (fixing now). I'll try to take a look at this this weekend or early next week.

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/MyRemindersFragment.java [hunk 1]
```diff
@@ -129,14 +138,29 @@ public void onDestroy() {
         super.onDestroy();
     }
 
+    private int currentSortOrder;
+    private static String sortBy;
+
+    private void setRiminderOrder() {
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/MyRemindersFragment.java]: Should be `setReminderOrder()`

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/MyRemindersFragment.java [hunk 2]
```diff
@@ -129,14 +138,29 @@ public void onDestroy() {
         super.onDestroy();
     }
 
+    private int currentSortOrder;
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/MyRemindersFragment.java]: Since these are member variables, could you please change to `mCurrentSortOrder`, etc.?

File: onebusaway-android/src/main/java/org/onebusaway/android/ui/MyRemindersFragment.java [hunk 3]
```diff
@@ -301,4 +325,68 @@ private void goToRoute(ListView l, int position) {
...
+    private void showSortByDialog() {
+        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
+        builder.setTitle(R.string.menu_option_sort_by);
+        currentSortOrder = PreferenceUtils.getReminderSortOrderFromPreferences();
+        builder.setSingleChoiceItems(R.array.sort_reminders, currentSortOrder,
+                new DialogInterface.OnClickListener() {
+                    @Override
+                    public void onClick(DialogInterface dialog, int which) {
+                        //if selected option is different, change option
+                        if (currentSortOrder != which) {
```
Comment (barbeau) [inline onebusaway-android/src/main/java/org/onebusaway/android/ui/MyRemindersFragment.java]: Could you please add a space after the `//` for all comments?

File: onebusaway-android/src/main/res/values/donottranslate.xml [hunk 4]
```diff
@@ -98,6 +99,12 @@
     <string name="analytics_label_sort_by_mfu_stops">Clicked sort by most frequently used from
         MyStarredStopsFragment
     </string>
+    <string name="analytics_label_sort_by_name_reminder">Clicked sort by name from
+        MyRemindersFragment
+    </string>
+    <string name="analytics_label_sort_by_time_reminder">Clicked sort by time from
```
Comment (barbeau) [inline onebusaway-android/src/main/res/values/donottranslate.xml]: Could you please change to `... by departure time... `?

Comment (barbeau) [reply onebusaway-android/src/main/res/values/donottranslate.xml]: Both string name and text.

**Comment by hayato1234** [comment]
Hi @barbeau , thank you for a quick review and reply! 
I fixed places where you mentioned. Let me know if anything else needs to be changed.

**Comment by barbeau** [comment]
Looks great, thanks @hayato1234!

**Comment by barbeau** [comment]
@hayato1234 If you'd like to be listed in the Contributors docs, could you please open a new PR with this?

Two places:
* https://github.com/OneBusAway/onebusaway-android/blob/master/CONTRIBUTORS.md
* https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/res/values/strings.xml#L776
